# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-09-25 09:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('axf', '0005_mainshow'),
    ]

    operations = [
        migrations.CreateModel(
            name='Market',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typeid', models.CharField(max_length=10)),
                ('typename', models.CharField(max_length=15)),
                ('childtypenames', models.CharField(max_length=100)),
                ('typesort', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'axf_axf_foodtypes',
            },
        ),
    ]
