# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-09-25 09:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('axf', '0006_market'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='market',
            table='axf_foodtypes',
        ),
    ]
