# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-09-25 09:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('axf', '0007_auto_20180925_0954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='market',
            name='childtypenames',
            field=models.CharField(max_length=200),
        ),
    ]
