# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-09-27 13:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('axf', '0010_auto_20180926_0837'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.CharField(max_length=12, unique=True)),
                ('password', models.CharField(max_length=200)),
                ('tel', models.CharField(max_length=20)),
                ('img', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=50)),
                ('token', models.CharField(max_length=100)),
            ],
        ),
    ]
