# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-09-28 12:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('axf', '0011_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('isselect', models.BooleanField(default=True)),
                ('good', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='axf.Goods')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='axf.User')),
            ],
        ),
    ]
