# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-09-28 13:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('axf', '0012_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='number',
            field=models.IntegerField(default=1),
        ),
    ]
